meta_product_name: "Match organizer"
meta_title: "Balr - The smoothest spontanious football organizer"
meta_description: "The easiest place to create a football team and spontanoius play football matches"
meta_image: "cover.png" # should exist in `app/assets/images/`
#twitter_account: "@BalrSportSweGer"    required for Twitter Cards
