meta_product_name: "Balrsport"
meta_title: "Balrsport - Spela och organisera fotboll idag"
meta_description: "Tillsammans revolutionerar vi svensk fotboll. Spela och organisera fotboll på Balrsport idag!"
meta_image: "cover.png" # should exist in `app/assets/images/`
#twitter_account: "@BalrSportSweGer"    required for Twitter Cards
